channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==2.7.1
  - cloudpickle==2.2.1
  - numpy==1.25.2
  - packaging==23.1
  - pandas==2.1.1
  - pyyaml==6.0.1
  - scipy==1.11.2
  - torch-geometric==2.3.1
  - torch==2.0.1
name: mlflow-env
